version: '3'

services:
  internal-chat:
    container_name: internal-chat
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    command: npm run start 8081
    networks:
      - yong-network

  web:
    container_name: internal-chat-web
    image: nginx:alpine
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginxvhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - internal-chat
    restart: always
    networks:
      - yong-network

networks:
  yong-network:
    external: true
    name: yong-network
